# Generated by Django 3.0.6 on 2020-05-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepagedesc_landingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_no', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Home Page Description',
            },
        ),
        migrations.DeleteModel(
            name='HomePageDesc',
        ),
        migrations.AlterModelOptions(
            name='landingpage',
            options={'verbose_name': 'LandingPageText', 'verbose_name_plural': 'LandingPageText'},
        ),
    ]
