# Generated by Django 3.0.6 on 2020-05-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200519_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesection',
            options={},
        ),
    ]
