# Generated by Django 3.0.6 on 2020-05-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founded_on', models.DateField()),
                ('server_type', models.CharField(choices=[('survival', 'survival'), ('creative', 'creative'), ('Hardcore', 'hardcore'), ('ultrahardcore', 'ultra hard core')], default='survival', max_length=200)),
                ('description', models.TextField()),
                ('features_description', models.TextField(blank=True, null=True)),
                ('rules_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minecraft.McServer')),
            ],
        ),
        migrations.CreateModel(
            name='ServerFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minecraft.McServer')),
            ],
        ),
        migrations.CreateModel(
            name='ServerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minecraft.McServer')),
            ],
        ),
    ]
