# Generated by Django 3.0.6 on 2020-05-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcserver',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
