# Generated by Django 3.0.6 on 2020-05-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0002_auto_20200513_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcserver',
            name='to_join_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
