# Generated by Django 3.0.6 on 2020-05-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0003_mcserver_to_join_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcserver',
            old_name='server_type',
            new_name='gamemode',
        ),
    ]
