# Generated by Django 3.0.6 on 2020-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0005_auto_20200513_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcserver',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
