# Generated by Django 3.0.6 on 2020-06-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0006_mcserver_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcserver',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
