# Generated by Django 3.0.6 on 2020-05-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Game')),
            ],
        ),
    ]
