# Generated by Django 3.0.6 on 2020-05-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Game'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
