# Generated by Django 3.0.6 on 2020-05-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0005_auto_20200513_1728'),
        ('gallery', '0002_auto_20200516_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='game',
        ),
        migrations.AddField(
            model_name='picture',
            name='minecraft_server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minecraft.McServer'),
        ),
    ]
